create table if not exists matches(
 id bigint generated by default as identity primary key,
 company_name text,
 tender_id text,
 fit_score numeric,
 details jsonb not null default '{}'::jsonb,
 created_at timestamptz default now()
);
create index if not exists idx_matches_company on matches(company_name);
create index if not exists idx_matches_tender on matches(tender_id);
