create table if not exists source_sync_runs(
 id bigint generated by default as identity primary key,
 source text not null,
 status text not null,
 records integer default 0,
 error text,
 created_at timestamptz default now()
);
create index if not exists idx_sync_source_created on source_sync_runs(source,created_at desc);

alter table tenders add column if not exists fingerprint text;
create unique index if not exists idx_tenders_fingerprint on tenders(fingerprint) where fingerprint is not null;
create index if not exists idx_tenders_source on tenders(source);

create table if not exists tender_versions(
 id bigint generated by default as identity primary key,
 tender_id text,
 fingerprint text,
 payload jsonb not null default '{}'::jsonb,
 created_at timestamptz default now()
);
create index if not exists idx_versions_tender on tender_versions(tender_id,created_at desc);
