create table if not exists companies(id bigint generated by default as identity primary key,company_name text not null,email text,pec_license text,profile jsonb not null default '{}'::jsonb,updated_at timestamptz default now());
create table if not exists tenders(id text primary key,title text not null,source text,payload jsonb not null default '{}'::jsonb,fingerprint text,updated_at timestamptz default now());
create table if not exists analyses(id bigint generated by default as identity primary key,tender_id text,company_name text,result jsonb not null,created_at timestamptz default now());
create table if not exists alerts(id bigint generated by default as identity primary key,tender_id text,recipient text,status text,created_at timestamptz default now());
